=== ajslater/comicbox/schemas/CoMet-v1.1.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!-- https://www.denvog.com/wordpress/comet/comet-specification/ -->
<xs:schema
  elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  version="1.1"
>
    <xs:element name="comet" type="cometType" />
    <xs:complexType name="cometType">
        <xs:all>
            <xs:element
        minOccurs="1"
        maxOccurs="1"
        name="title"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="1"
        name="description"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="1"
        name="series"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="1"
        name="issue"
        type="xs:nonNegativeInteger"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="1"
        name="volume"
        type="xs:nonNegativeInteger"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="1"
        name="publisher"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="1"
        name="date"
        type="xs:date"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="unbounded"
        name="genre"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="unbounded"
        name="character"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="1"
        name="isVersionOf"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="1"
        name="price"
        type="xs:decimal"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="1"
        name="format"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="1"
        name="language"
        type="xs:language"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="1"
        name="rating"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="1"
        name="rights"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="1"
        name="identifier"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="1"
        name="pages"
        type="xs:nonNegativeInteger"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="unbounded"
        name="creator"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="unbounded"
        name="writer"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="unbounded"
        name="penciller"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="unbounded"
        name="editor"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="1"
        name="coverDesigner"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="unbounded"
        name="letterer"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="unbounded"
        name="inker"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="unbounded"
        name="colorist"
        type="xs:string"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="unbounded"
        name="coverImage"
        type="xs:anyURI"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="1"
        name="lastMark"
        type="xs:nonNegativeInteger"
      />
            <xs:element
        minOccurs="0"
        maxOccurs="1"
        name="readingDirection"
        type="readingDirectionType"
      />
        </xs:all>
    </xs:complexType>
    <xs:simpleType name="readingDirectionType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ltr" />
            <xs:enumeration value="rtl" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ajslater/comicbox/tests/files/metadata/comet.xml
<?xml version="1.0" encoding="UTF-8"?>
<comet xmlns:comet="http://www.denvog.com/comet/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.denvog.com/comet/ https://github.com/ajslater/comicbox/blob/main/schemas/CoMet-v1.1.xsd">
	<character>Captain Science</character>
	<character>Gordon Dane</character>
	<coverImage>CaptainScience#1_01.jpg</coverImage>
	<date>1950-12-01</date>
	<description>A long example description</description>
	<format>Comic</format>
	<genre>Science Fiction</genre>
	<identifier>CVDB145269</identifier>
	<isVersionOf>Captain Science Alternate #001</isVersionOf>
	<issue>1</issue>
	<language>en</language>
	<lastMark>4</lastMark>
	<pages>5</pages>
	<penciller>Wally Wood</penciller>
	<price>0.10</price>
	<publisher>Bell Features</publisher>
	<rating>Teen</rating>
	<readingDirection>ltr</readingDirection>
	<rights>Copyright (c) 1950 Bell Features</rights>
	<series>Captain Science</series>
	<title>The Beginning</title>
	<volume>1</volume>
	<writer>Joe Orlando</writer>
</comet>

=== ajslater/comicbox/tests/files/export/comet.xml
<?xml version="1.0" encoding="UTF-8"?>
<comet xmlns:comet="http://www.denvog.com/comet/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.denvog.com/comet/ https://github.com/ajslater/comicbox/blob/main/schemas/CoMet-v1.1.xsd">
	<character>Captain Science</character>
	<character>Gordon Dane</character>
	<date>1950-11-01</date>
	<genre>Science Fiction</genre>
	<identifier>urn:comicvine:145269</identifier>
	<inker>Wally Wood</inker>
	<issue>1</issue>
	<language>en</language>
	<pages>0</pages>
	<penciller>Wally Wood</penciller>
	<publisher>Youthful Adventure Stories</publisher>
	<series>Captain Science</series>
	<title>The Beginning</title>
	<volume>1950</volume>
	<writer>Joe Orlando</writer>
</comet>
